Update/alamofire 5 0 0
Yalantis/APIClient pull request #32
Opened 2022-08-03 07:44 UTC by AlexanderBerezovskyi

2022-08-03 07:56 UTC, MykhailenkoValerii commented on APIClient/Alamofire/AlamofireRequestExecutor.swift
> +              return
enter before return

2022-08-03 07:57 UTC, sergey-prikhodko commented on APIClient/Default/Request/APIRequest.swift
> +    func append(_ stream: InputStream, withLength length: UInt64, headers: HTTPHeaders)
такий момент, HTTPHeaders це сутність аламофаєра, а одна з функцій клієнта це абстрагуватись від нього, щоб не треба було імпортувати його в проект, треба зробити або тайпаліас якийсь або аналогічний інтерфейс

2022-08-03 08:02 UTC, sergey-prikhodko requested changes
виглядає так що в деякийх місцях таб з 2 пробілів, а в інших 4, треба привести до одного вигляду, приоритетно до 4 бо так усюди по прокекту

2022-08-03 08:02 UTC, sergey-prikhodko commented on APIClient/Alamofire/AlamofireRequestExecutor.swift
> +        }
є пропозиція винести клоужери в проперті щоб не писати 2 клоужери один за іншим, так буде красивіше )

2022-08-03 08:02 UTC, sergey-prikhodko commented on YALAPIClient.podspec
> +    ss.dependency 'Alamofire', '5.0'
краще до останньої версії підняти

2022-08-08 10:53 UTC, AlexanderBerezovskyi commented on APIClient/Alamofire/AlamofireRequestExecutor.swift
> +        }
це серйозна зміна, бо по проекту саме так усюди, я б поки лишив

2022-08-09 12:47 UTC, sergey-prikhodko approved these changes

2022-08-09 13:04 UTC, merged